name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and Deploy
        run: |
          echo "No build step needed for static site"
          echo "Deploying to GitHub Pages"
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git commit --allow-empty -m "Trigger GitHub Pages deployment"
          git push origin main
